### ISSUE TITLE
Lots of errors on startup

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#160]
perhaps wrong debug level is set?  Seems like the last error is real?

[INFO   ] [Logger      ] Record log in C:\Users\Lumaview Pro\.kivy\logs\kivy_23-01-16_5.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.2
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.1
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.4.5
[INFO   ] [Kivy        ] v2.1.0
[INFO   ] [Kivy        ] Installed at "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\python.exe"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 189 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 - Build 30.0.101.3111'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) UHD Graphics'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 - Build 30.0.101.3111'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
LED Controller at COM4
LEDBoard.connect() succeeded
Motor Controller at COM10
TrinamicBoard.connect()

-----------------------------------------
Latest Code Change: 1/14/2023
Run Time: 2023 01 16 17:28:26
-----------------------------------------
LumaViewProApp.build()
 Traceback (most recent call last):
   File "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\core\window\window_sdl2.py", line 270, in _event_filter
     EventLoop.idle()
   File "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\base.py", line 379, in idle
     Clock.tick()
   File "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\clock.py", line 733, in tick
     self.post_idle(ts, self.idle())
   File "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\clock.py", line 776, in post_idle
     self._process_events()
   File "kivy\_clock.pyx", line 620, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 653, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
   File "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in create_window
     super(WindowSDL, self).create_window()
   File "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\core\window\__init__.py", line 1460, in create_window
     self.dispatch('on_pre_resize', *self.size)
   File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\core\window\__init__.py", line 1709, in on_pre_resize
     self.dispatch('on_resize', width, height)
   File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
   File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
   File "C:\Users\Lumaview Pro\Downloads\LumaViewPro-master-2023-01-16\LumaViewPro-master\lumaviewpro.py", line 2651, in _on_resize
     Clock.schedule_once(lumaview.ids['motionsettings_id'].check_settings, 0.1)
 NameError: name 'lumaview' is not defined
 Exception ignored in: 'kivy.core.window._window_sdl2._WindowSDL2Storage.cb_event_filter'
 Traceback (most recent call last):
   File "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\core\window\window_sdl2.py", line 270, in _event_filter
     EventLoop.idle()
   File "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\base.py", line 379, in idle
     Clock.tick()
   File "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\clock.py", line 733, in tick
     self.post_idle(ts, self.idle())
   File "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\clock.py", line 776, in post_idle
     self._process_events()
   File "kivy\_clock.pyx", line 620, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 653, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
   File "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in create_window
     super(WindowSDL, self).create_window()
   File "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\core\window\__init__.py", line 1460, in create_window
     self.dispatch('on_pre_resize', *self.size)
   File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\core\window\__init__.py", line 1709, in on_pre_resize
     self.dispatch('on_resize', width, height)
   File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
   File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
   File "C:\Users\Lumaview Pro\Downloads\LumaViewPro-master-2023-01-16\LumaViewPro-master\lumaviewpro.py", line 2651, in _on_resize
     Clock.schedule_once(lumaview.ids['motionsettings_id'].check_settings, 0.1)
 NameError: name 'lumaview' is not defined
ShaderViewer.__init__()
ScopeDisplay.__init__()
ScopeDisplay.start()
Clock.schedule_interval(self.update, 1.0 / self.fps)
MotionSettings.__init__()
VerticalControl.__init__()
ModSlider.__init__()
[INFO   ] [GL          ] NPOT texture support is available
Stage.__init__()
ProtocolSettings.__init__()
Stage.__init__()
MainSettings.__init__()
MicroscopeSettings.__init__()
LayerControl.__init__()
ModSlider.__init__()
ModSlider.__init__()
ModSlider.__init__()
Histogram.__init__()
LayerControl.__init__()
ModSlider.__init__()
ModSlider.__init__()
ModSlider.__init__()
Histogram.__init__()
LayerControl.__init__()
ModSlider.__init__()
ModSlider.__init__()
ModSlider.__init__()
Histogram.__init__()
LayerControl.__init__()
ModSlider.__init__()
ModSlider.__init__()
ModSlider.__init__()
Histogram.__init__()
MicroscopeSettings.load_settings()
MicroscopeSettings.select_scope()
MicroscopeSettings.select_objective()
ProtocolSettings.select_labware()
LayerControl.root_text()
LayerControl.root_text()
LayerControl.root_text()
LayerControl.root_text()
<pypylon.pylon.InstantCamera; proxy of <Swig Object of type 'Pylon::CInstantCamera *' at 0x0000016D96C9B3C0> >
PylonCamera.frame_size(1900,1900); succeeded
ProtocolSettings.load_protocol()
LayerControl.apply_settings()
LEDBoard.send_command(LEDS_OFF) succeeded
<pypylon.pylon.InstantCamera; proxy of <Swig Object of type 'Pylon::CInstantCamera *' at 0x0000016D96C9B3C0> >
PylonCamera.auto_gain(False): succeeded
<pypylon.pylon.InstantCamera; proxy of <Swig Object of type 'Pylon::CInstantCamera *' at 0x0000016D96C9B3C0> >
PylonCamera.gain(1.0): succeeded
PylonCamera.exposure_t(30.0): succeeded
LEDBoard.send_command(LEDS_OFF) succeeded
XYStageControl.home()
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "C:\Users\Lumaview Pro\Downloads\LumaViewPro-master-2023-01-16\LumaViewPro-master\lumaviewpro.py", line 2669, in <module>
     LumaViewProApp().run()
   File "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\app.py", line 955, in run
     runTouchApp()
   File "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\base.py", line 339, in mainloop
     self.idle()
   File "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\base.py", line 379, in idle
     Clock.tick()
   File "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\clock.py", line 733, in tick
     self.post_idle(ts, self.idle())
   File "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\clock.py", line 776, in post_idle
     self._process_events()
   File "kivy\_clock.pyx", line 620, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 653, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
   File "C:\Users\Lumaview Pro\Downloads\LumaViewPro-master-2023-01-16\LumaViewPro-master\lumaviewpro.py", line 171, in update
     texture = Texture.create(size=(array.shape[1],array.shape[0]), colorfmt='luminance')
 IndexError: tuple index out of range

**Comment by ericweiner** [comment]
Definitely real- it crashes and will not startup.

**Comment by ericweiner** [comment]
Tried power cycling board and reunzipping code, it still persists.

**Comment by ericweiner** [comment]
This crash at the end could potentially be bad hardware.  I'm closing this for now.
