### ISSUE TITLE
Script example needs updating

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#162]
Currently there are errors in this when I run it.  Did a function name get updated?

Traceback (most recent call last):
  File "C:\Users\Lumaview Pro\Downloads\LumaViewPro-2023-01-18\LumaViewPro-master\script_example.py", line 39, in <module>
    xyz.move_abs_pos('Z', 3270)    # move to absolute position in um
  File "C:\Users\Lumaview Pro\Downloads\LumaViewPro-2023-01-18\LumaViewPro-master\trinamic850.py", line 278, in move_abs_pos
    current = self.current_pos('Z')
  File "C:\Users\Lumaview Pro\Downloads\LumaViewPro-2023-01-18\LumaViewPro-master\trinamic850.py", line 241, in current_pos
    pos = int( self.exchange_command('ACTUAL_R' + axis) )
ValueError: invalid literal for int() with base 10: 'ACTUAL_RZ'

**Comment by ericweiner** [comment]
if you run the script, it will put the system in a bad state so that it requires a power cycle in order to work.  
you get this same error on startup of LumaView.

File "C:\Users\Lumaview Pro\Downloads\LumaViewPro-2023-01-18\LumaViewPro-master\trinamic850.py", line 241, in current_pos
pos = int( self.exchange_command('ACTUAL_R' + axis) )
ValueError: invalid literal for int() with base 10: 'ACTUAL_RZ'

**Comment by iwaniec** [comment]
Sample script should be working now.
