### ISSUE TITLE
Many errors on startup every time

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#169]
I think we need to clean this up.   The last error is also a real one, it is not letting the system start up.  

 Traceback (most recent call last):
   File "C:\Users\Eric Weiner\Downloads\LumaViewPro-master-2023-01-24\LumaViewPro-master\lumaviewpro.py", line 2719, in <module>
     LumaViewProApp().run()
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\app.py", line 955, in run
     runTouchApp()
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\base.py", line 339, in mainloop
     self.idle()
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\base.py", line 379, in idle
     Clock.tick()
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\clock.py", line 733, in tick
     self.post_idle(ts, self.idle())
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\clock.py", line 776, in post_idle
     self._process_events()
   File "kivy\_clock.pyx", line 620, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 653, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
   File "C:\Users\Eric Weiner\Downloads\LumaViewPro-master-2023-01-24\LumaViewPro-master\lumaviewpro.py", line 2080, in draw_labware
     x_target = lumaview.motion.target_pos('X')
  

 File "C:\Users\Eric Weiner\Downloads\LumaViewPro-master-2023-01-24\LumaViewPro-master\trinamic850.py", line 238, in target_pos
     pos = int( self.exchange_command('TARGET_R' + axis ) )
 ValueError: invalid literal for int() with base 10: ''

**Comment by ericweiner** [comment]
I'm breaking the last error into a separate issue as that is a crash on startup.  (#171 )

**Comment by ericweiner** [comment]
I'm closing this, these are long gone.
