### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#170]
Latest version (as of 10:20AM, 2023-01-25)

Crash on startup.

 Traceback (most recent call last):
   File "C:\Users\Eric Weiner\Downloads\LumaViewPro-master-2023-01-25-morning\LumaViewPro-master\lumaviewpro.py", line 2731, in <module>
     LumaViewProApp().run()
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\app.py", line 955, in run
     runTouchApp()
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\base.py", line 339, in mainloop
     self.idle()
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\base.py", line 379, in idle
     Clock.tick()
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\clock.py", line 733, in tick
     self.post_idle(ts, self.idle())
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\clock.py", line 776, in post_idle
     self._process_events()
   File "kivy\_clock.pyx", line 620, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 653, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
   File "C:\Users\Eric Weiner\Downloads\LumaViewPro-master-2023-01-25-morning\LumaViewPro-master\lumaviewpro.py", line 181, in update
     texture = Texture.create(size=(array.shape[1],array.shape[0]), colorfmt='luminance')
 NameError: name 'Texture' is not defined. Did you mean: 'texture'?

**Comment by hickerson** [comment]
Should be fixed now.

**Comment by hickerson** [comment]
Fixed.
