### ISSUE TITLE
Occasional crash on startup

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#171]
I'm doing a lot of startups right now while testing the Z axis.  I see this about 10% of the time on a startup which causes a fatal crash.  I don't know what specifically it is seeing at this point, maybe we can add some extra validation around this data input?

(breaking this out from issue #169 )

File "C:\Users\Eric Weiner\Downloads\LumaViewPro-master-2023-01-24\LumaViewPro-master\trinamic850.py", line 238, in target_pos
pos = int( self.exchange_command('TARGET_R' + axis ) )
ValueError: invalid literal for int() with base 10: ''

**Comment by ericweiner** [comment]
Further details- I _think_ every time I have seen this it is on a fresh startup.  Then when I re-run LV Pro, it comes up ok.

**Comment by hickerson** [comment]
Not seeing this line of code anymore.

**Comment by hickerson** [comment]
Error has been updated to be more clear what is happening but may still happen. Old error reporting was vauge. Problem is likely caused by making too many requests to the Trinamic board while homing (say, by requesting another motion.) To truly fix this a Trinamic pico update will likely also be needed. Also a a better way to ignore these requests (such as an internal BUSY flag) should be added.

**Comment by ericweiner** [comment]
still getting an error.

 Traceback (most recent call last):
   File "C:\Users\Eric Weiner\Downloads\LumaViewPro-2023-01-26-3pm\LumaViewPro-master\lumaviewpro.py", line 2754, in <module>
     LumaViewProApp().run()
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\app.py", line 955, in run
     runTouchApp()
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\base.py", line 339, in mainloop
     self.idle()
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\base.py", line 379, in idle
     Clock.tick()
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\clock.py", line 733, in tick
     self.post_idle(ts, self.idle())
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\clock.py", line 776, in post_idle
     self._process_events()
   File "kivy\_clock.pyx", line 620, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 653, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
   File "C:\Users\Eric Weiner\Downloads\LumaViewPro-2023-01-26-3pm\LumaViewPro-master\lumaviewpro.py", line 2111, in draw_labware
     x_target, y_target = protocol_settings.stage_to_plate(x_target, y_target)
 UnboundLocalError: local variable 'x_target' referenced before assignment

**Comment by ericweiner** [comment]
FYI- I have determined the source of the error.  You were correct.  There was something subtly wrong with the firmware so it wasn't starting up correctly.  A way to test this there is to just delete the firmware.  (i.e. so it will be detecting the serial port but the firmware will not respond.  That is basically what was happening here.)  It should come up with a "cannot communicate with motor controller error or similar.
