### ISSUE TITLE
script_example.py needs to be updated to new API

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#213]
Hopefully just a matter of changing the "import" callouts at top?  

Right now it fails on startup.

**Comment by ericweiner** [comment]
It looks like it is now mostly working.  It does require pillow to be installed.  Is LumaviewPro also using this?  (i.e. do we need to add it to the main install doc?) 

I am getting a lot of errors related to the logger functionality.  Is there another pip that we need to install for that?

**Comment by ericweiner** [comment]
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 1100, in emit
    msg = self.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Users\Eric Weiner\Downloads\LumaViewPro-main-2023-04-11\LumaViewPro-main\lvp_logger.py", line 56, in format
    return record.getMessage()
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:\Users\Eric Weiner\Downloads\LumaViewPro-main-2023-04-11\LumaViewPro-main\script_example.py", line 19, in <module>
    scope = lumascope_api.Lumascope()
  File "C:\Users\Eric Weiner\Downloads\LumaViewPro-main-2023-04-11\LumaViewPro-main\lumascope_api.py", line 63, in __init__
    self.led = LEDBoard()
  File "C:\Users\Eric Weiner\Downloads\LumaViewPro-main-2023-04-11\LumaViewPro-main\ledboard.py", line 56, in __init__
    logger.info('[LED Class ] LED Controller at', port.device)
Message: '[LED Class ] LED Controller at'
Arguments: ('COM18',)
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 1100, in emit
    msg = self.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Users\Eric Weiner\Downloads\LumaViewPro-main-2023-04-11\LumaViewPro-main\lvp_logger.py", line 56, in format
    return record.getMessage()
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:\Users\Eric Weiner\Downloads\LumaViewPro-main-2023-04-11\LumaViewPro-main\script_example.py", line 19, in <module>
    scope = lumascope_api.Lumascope()
  File "C:\Users\Eric Weiner\Downloads\LumaViewPro-main-2023-04-11\LumaViewPro-main\lumascope_api.py", line 70, in __init__
    self.motion = MotorBoard()
  File "C:\Users\Eric Weiner\Downloads\LumaViewPro-main-2023-04-11\LumaViewPro-main\motorboard.py", line 60, in __init__
    logger.info('[XYZ Class ] Motor Controller at', port.device)
Message: '[XYZ Class ] Motor Controller at'
Arguments: ('COM22',)

**Comment by ericweiner** [comment]
Not relevant, we need to make a new example.
