### ISSUE TITLE
Crash when changing frame size on latest version

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#295]
Using the python code, downloaded on 10/24/23

Crash when changing the frame size to anything else.  (I tried more and less than 1900 pixels).  Crash when you hit return. 
Nothing is in logfile.  The stack trace is in the console only. 

 ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "C:\Users\Eric Weiner\Downloads\LumaViewPro-main-2023-10-24\LumaViewPro-main\lumaviewpro.py", line 3868, in <module>
     LumaViewProApp().run()
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\app.py", line 955, in run
     runTouchApp()
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\base.py", line 341, in mainloop
     self.window.mainloop()
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\core\window\window_sdl2.py", line 757, in mainloop
     if self.dispatch('on_key_down', key,
   File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
   File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\core\window\__init__.py", line 163, in _on_window_key_down
     return self.dispatch('on_key_down', keycode, text, modifiers)
   File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
   File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\uix\textinput.py", line 2941, in keyboard_on_key_down
     self._key_down(key)
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\uix\textinput.py", line 2847, in _key_down
     self.dispatch('on_text_validate')
   File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
   File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1191, in kivy._event.EventObservers._dispatch
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\lang\builder.py", line 55, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "C:\Users\Eric Weiner\Downloads\LumaViewPro-main-2023-10-24\LumaViewPro-main\lumaviewpro.kv", line 1574, in <module>
     on_text_validate: root.frame_size()
   File "C:\Users\Eric Weiner\Downloads\LumaViewPro-main-2023-10-24\LumaViewPro-main\lumaviewpro.py", line 3309, in frame_size
     w = int(self.ids['frame_width'].text)
 KeyError: 'frame_width'

**Comment by jmcoreymv** [comment]
Fixed on https://github.com/EtalumaSupport/LumaViewPro/pull/298.
