### ISSUE TITLE
crash in feature/tiling branch

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#302]
Crash when you click on "new" in protocol. 
does not get written to log file, only to console. 

[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "C:\Users\Eric Weiner\Downloads\LumaViewPro-feature-tiling\lumaviewpro.py", line 4046, in <module>
     LumaViewProApp().run()
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\app.py", line 955, in run
     runTouchApp()
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\base.py", line 339, in mainloop
     self.idle()
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\base.py", line 383, in idle
     self.dispatch_input()
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\base.py", line 334, in dispatch_input
     post_dispatch_input(*pop(0))
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\base.py", line 302, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
   File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1191, in kivy._event.EventObservers._dispatch
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\lang\builder.py", line 55, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "C:\Users\Eric Weiner\Downloads\LumaViewPro-feature-tiling\lumaviewpro.kv", line 875, in <module>
     on_release: root.new_protocol()
   File "C:\Users\Eric Weiner\Downloads\LumaViewPro-feature-tiling\lumaviewpro.py", line 2287, in new_protocol
     self.ids['step_name_input'].text = self.step_names[0]
 IndexError: list index out of range

**Comment by jmcoreymv** [comment]
I was able to recreate this crash by clicking 'New' in protocol if no steps were part of the protocol (i.e. all the channels were set to not acquire).  Was this the context in which you encountered the crash?  If so, I've pushed an update, please test and let me know if it resolves the crash.

**Comment by jmcoreymv** [comment]
Fixed on https://github.com/EtalumaSupport/LumaViewPro/pull/303
