### ISSUE TITLE
Crash on launch of latest python code

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#305]
Looks like a Kivy error.

[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
C:\Users\Eric Weiner\Downloads\LumaViewPro-main-2023-11-27\LumaViewPro-main\
 Traceback (most recent call last):
   File "C:\Users\Eric Weiner\Downloads\LumaViewPro-main-2023-11-27\LumaViewPro-main\lumaviewpro.py", line 4069, in <module>
     LumaViewProApp().run()
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\app.py", line 954, in run
     self._run_prepare()
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\app.py", line 923, in _run_prepare
     self.load_kv(filename=self.kv_file)
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\app.py", line 696, in load_kv
     root = Builder.load_file(rfilename)
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\lang\builder.py", line 305, in load_file
     return self.load_string(data, **kwargs)
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\lang\builder.py", line 372, in load_string
     parser = Parser(content=string, filename=fn)
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\lang\parser.py", line 483, in __init__
     self.parse(content)
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\lang\parser.py", line 593, in parse
     objects, remaining_lines = self.parse_level(0, lines)
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\lang\parser.py", line 675, in parse_level
     current_object = ParserRule(self, ln, name, rlevel)
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\lang\parser.py", line 335, in __init__
     self._detect_selectors()
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\lang\parser.py", line 377, in _detect_selectors
     self._build_rule()
   File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\kivy\lang\parser.py", line 392, in _build_rule
     raise ParserException(self.ctx, self.line,
 kivy.lang.parser.ParserException: Parser: File "C:\Users\Eric Weiner\Downloads\LumaViewPro-main-2023-11-27\LumaViewPro-main\lumaviewpro.kv", line 1246:
 ...
    1244:                       on_collapse: root.accordion_collapse()
    1245:
 >> 1246:<<<<<<< HEAD
    1247:            BoxLayout:
    1248:                padding: '5dp'
 ...
 Invalid rule (must be inside <>)

**Comment by jmcoreymv** [comment]
@hickerson I think this was due to a recent commit that was checked in to main.  Was this cleaned up?

**Comment by ericweiner** [comment]
We need to either get this reverted or fixed ASAP.

**Comment by jmcoreymv** [comment]
@ericweiner I backed out those ~5 recent commits. Should be resolved.
