### ISSUE TITLE
Add support for Basler Ace cameras

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#311]
At moment, LV Pro does not detect Basler Ace cameras, only Darts. it would be nice to add this, when we can.  (it may be as simple as just allowing them?  I don't see anything obvious in the code preventing this.

**Comment by ericweiner** [comment]
Testing acA1920-155um with the ace branch.  It appears to work!


Testing acA4024-29um.  (12MP camera) with the Ace branch.  

Get this error
[lumaviewpro.log](https://github.com/EtalumaSupport/LumaViewPro/files/14428480/lumaviewpro.log)

[INFO] 02/27/2024 19:27:01.008 - pyloncamera.py - [CAM Class ] PylonCamera.__init__()
[ERROR] 02/27/2024 19:27:01.504 - pyloncamera.py - [CAM Class ] PylonCamera.connect() failed
Traceback (most recent call last):
  File "C:\Users\Eric Weiner\Downloads\LumaViewPro-feature-support-cam-acA1920\pyloncamera.py", line 81, in connect
    self._center()
  File "C:\Users\Eric Weiner\Downloads\LumaViewPro-feature-support-cam-acA1920\pyloncamera.py", line 61, in _center
    self.active.BslCenterX.Execute()
  File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\pypylon\pylon.py", line 4287, in __getattr__
    return self.GetNodeMap().GetNode(attribute)
  File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\pypylon\genicam.py", line 1357, in GetNode
    return _genicam.INodeMap_GetNode(self, Name)
_genicam.LogicalErrorException: Node not existing (file 'genicam_wrap.cpp', line 16130)




I get the same error when I try it back in the "main" branch
[INFO] 02/27/2024 19:33:50.292 - pyloncamera.py - [CAM Class ] PylonCamera.__init__()
[ERROR] 02/27/2024 19:33:50.803 - pyloncamera.py - [CAM Class ] PylonCamera.connect() failed
Traceback (most recent call last):
  File "C:\Users\Eric Weiner\Downloads\LumaViewPro-dev-jcorey-2024-02-22\LumaViewPro-dev-jcorey\pyloncamera.py", line 64, in connect
    self.active.BslCenterX.Execute()
  File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\pypylon\pylon.py", line 4287, in __getattr__
    return self.GetNodeMap().GetNode(attribute)
  File "C:\Users\Eric Weiner\AppData\Roaming\Python\Python310\site-packages\pypylon\genicam.py", line 1357, in GetNode
    return _genicam.INodeMap_GetNode(self, Name)
_genicam.LogicalErrorException: Node not existing (file 'genicam_wrap.cpp', line 16130)

**Comment by ericweiner** [comment]
Latest update now solves acA4024-29um. issue, it provides an image now.  (I did not verify the direction yet as it wasn't installed in an optics module. )

**Comment by ericweiner** [comment]
This works now.
