### ISSUE TITLE
LED controller- serial com timeout

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#330]
There was a write timeout on the serial port, followed by a capture of a dark image.  It did successfully reconnect to the LED controller on the next image.  This is a problem that I have seen very occasionally.  

I would like to address this in two ways. 

Let's increase the timeout from 0.01 to a higher value.  I am trying 0.05 sec now. 
Let's change logic so that it retries this communication THEN takes the image.  

Please see log starting at  16:44:40.134

[INFO] 02/27/2024 16:44:35.210 - ledboard.py - [LED Class ] LEDBoard.exchange_command(LEDS_OFF) succeeded: 'RE: LEDS_OFF\r\n'
[INFO] 02/27/2024 16:44:35.210 - pyloncamera.py - [CAM Class ] PylonCamera.gain(5.0): succeeded
[INFO] 02/27/2024 16:44:35.225 - pyloncamera.py - [CAM Class ] PylonCamera.exposure_t(25.0): succeeded
[INFO] 02/27/2024 16:44:35.225 - ledboard.py - [LED Class ] LEDBoard.exchange_command(LED3_30) succeeded: 'RE: LEDS_OFF\r\n'
[INFO] 02/27/2024 16:44:35.225 - pyloncamera.py - [CAM Class ] PylonCamera.get_exposure_t(): succeeded
[INFO] 02/27/2024 16:44:35.475 - ledboard.py - [LED Class ] LEDBoard.exchange_command(LEDS_OFF) succeeded: ' turned off\r\n'
[INFO] 02/27/2024 16:44:35.538 - lumascope_api.py - [SCOPE API ] Lumascope.focus_function()
[INFO] 02/27/2024 16:44:35.601 - lumascope_api.py - [SCOPE API ] Focus Score Vollath: 3533693.0
[INFO] 02/27/2024 16:44:36.855 - ledboard.py - [LED Class ] LEDBoard.exchange_command(LEDS_OFF) succeeded: 'RE: LEDS_OFF\r\n'
[INFO] 02/27/2024 16:44:36.855 - pyloncamera.py - [CAM Class ] PylonCamera.gain(5.0): succeeded
[INFO] 02/27/2024 16:44:36.871 - pyloncamera.py - [CAM Class ] PylonCamera.exposure_t(25.0): succeeded
[INFO] 02/27/2024 16:44:36.871 - ledboard.py - [LED Class ] LEDBoard.exchange_command(LED3_30) succeeded: 'RE: LEDS_OFF\r\n'
[INFO] 02/27/2024 16:44:36.871 - pyloncamera.py - [CAM Class ] PylonCamera.get_exposure_t(): succeeded
[INFO] 02/27/2024 16:44:37.122 - ledboard.py - [LED Class ] LEDBoard.exchange_command(LEDS_OFF) succeeded: 'ED 1 has been turned off\r\n'
[INFO] 02/27/2024 16:44:37.185 - lumascope_api.py - [SCOPE API ] Lumascope.focus_function()
[INFO] 02/27/2024 16:44:37.247 - lumascope_api.py - [SCOPE API ] Focus Score Vollath: 3523689.0
[INFO] 02/27/2024 16:44:38.488 - ledboard.py - [LED Class ] LEDBoard.exchange_command(LEDS_OFF) succeeded: 'RE: LEDS_OFF\r\n'
[INFO] 02/27/2024 16:44:38.488 - pyloncamera.py - [CAM Class ] PylonCamera.gain(5.0): succeeded
[INFO] 02/27/2024 16:44:38.488 - pyloncamera.py - [CAM Class ] PylonCamera.exposure_t(25.0): succeeded
[INFO] 02/27/2024 16:44:38.488 - ledboard.py - [LED Class ] LEDBoard.exchange_command(LED3_30) succeeded: 'RE: LEDS_OFF\r\n'
[INFO] 02/27/2024 16:44:38.503 - pyloncamera.py - [CAM Class ] PylonCamera.get_exposure_t(): succeeded
[INFO] 02/27/2024 16:44:38.756 - ledboard.py - [LED Class ] LEDBoard.exchange_command(LEDS_OFF) succeeded: 'LED 0 has been turned off\r\n'
[INFO] 02/27/2024 16:44:38.834 - lumascope_api.py - [SCOPE API ] Lumascope.focus_function()
[INFO] 02/27/2024 16:44:38.897 - lumascope_api.py - [SCOPE API ] Focus Score Vollath: 3509759.0
[INFO] 02/27/2024 16:44:40.119 - ledboard.py - [LED Class ] LEDBoard.exchange_command(LEDS_OFF) succeeded: 'RE: LEDS_OFF\r\n'
[INFO] 02/27/2024 16:44:40.119 - pyloncamera.py - [CAM Class ] PylonCamera.gain(5.0): succeeded
[INFO] 02/27/2024 16:44:40.119 - pyloncamera.py - [CAM Class ] PylonCamera.exposure_t(25.0): succeeded
[ERROR] 02/27/2024 16:44:40.134 - ledboard.py - [LED Class ] LEDBoard.exchange_command(LED3_30) Serial Timeout Occurred
Traceback (most recent call last):
  File "C:\Users\chris\Downloads\LumaViewPro-main-2024-02-23\LumaViewPro-main\ledboard.py", line 109, in exchange_command
    self.driver.write(stream)
  File "C:\Users\chris\AppData\Roaming\Python\Python310\site-packages\serial\serialwin32.py", line 325, in write
    raise SerialTimeoutException('Write timeout')
serial.serialutil.SerialTimeoutException: Write timeout
[INFO] 02/27/2024 16:44:40.134 - pyloncamera.py - [CAM Class ] PylonCamera.get_exposure_t(): succeeded
[INFO] 02/27/2024 16:44:40.384 - ledboard.py - [LED Class ] Found LED controller and about to create driver.
[INFO] 02/27/2024 16:44:40.384 - ledboard.py - [LED Class ] LEDBoard.connect() succeeded
[INFO] 02/27/2024 16:44:40.415 - lumascope_api.py - [SCOPE API ] Lumascope.focus_function()
[INFO] 02/27/2024 16:44:40.478 - lumascope_api.py - [SCOPE API ] Focus Score Vollath: 4.0
[INFO] 02/27/2024 16:44:41.715 - ledboard.py - [LED Class ] LEDBoard.exchange_command(LEDS_OFF) succeeded: 'LED 2 has been turned off\r\n'
[INFO] 02/27/2024 16:44:41.715 - pyloncamera.py - [CAM Class ] PylonCamera.gain(5.0): succeeded
[INFO] 02/27/2024 16:44:41.730 - pyloncamera.py - [CAM Class ] PylonCamera.exposure_t(25.0): succeeded
[INFO] 02/27/2024 16:44:41.730 - ledboard.py - [LED Class ] LEDBoard.exchange_command(LED3_30) succeeded: 'RE: LEDS_OFF\r\n'
[INFO] 02/27/2024 16:44:41.730 - pyloncamera.py - [CAM Class ] PylonCamera.get_exposure_t(): succeeded
[INFO] 02/27/2024 16:44:41.996 - ledboard.py - [LED Class ] LEDBoard.exchange_command(LEDS_OFF) succeeded: 'ED 1 has been turned off\r\n'
[INFO] 02/27/2024 16:44:42.060 - lumascope_api.py - [SCOPE API ] Lumascope.focus_function()
[INFO] 02/27/2024 16:44:42.106 - lumascope_api.py - [SCOPE API ] Focus Score Vollath: 3461239.0
[INFO] 02/27/2024 16:44:43.344 - ledboard.py - [LED Class ] LEDBoard.exchange_command(LEDS_OFF) succeeded: 'RE: LEDS_OFF\r\n'
[INFO] 02/27/2024 16:44:43.344 - pyloncamera.py - [CAM Class ] PylonCamera.gain(5.0): succeeded
[INFO] 02/27/2024 16:44:43.359 - pyloncamera.py - [CAM Class ] PylonCamera.exposure_t(25.0): succeeded
[INFO] 02/27/2024 16:44:43.359 - ledboard.py - [LED Class ] LEDBoard.exchange_command(LED3_30) succeeded: 'RE: LEDS_OFF\r\n'
[INFO] 02/27/2024 16:44:43.359 - pyloncamera.py - [CAM Class ] PylonCamera.get_exposure_t(): succeeded
[INFO] 02/27/2024 16:44:43.609 - ledboard.py - [LED Class ] LEDBoard.exchange_command(LEDS_OFF) succeeded: 'ED 1 has been turned off\r\n'
[INFO] 02/27/2024 16:44:43.687 - lumascope_api.py - [SCOPE API ] Lumascope.focus_function()
[INFO] 02/27/2024 16:44:43.734 - lumascope_api.py - [SCOPE API ] Focus Score Vollath: 3443999.0
[INFO] 02/27/2024 16:44:44.988 - ledboard.py - [LED Class ] LEDBoard.exchange_command(LEDS_OFF) succeeded: 'RE: LEDS_OFF\r\n'
[INFO] 02/27/2024 16:44:44.988 - pyloncamera.py - [CAM Class ] PylonCamera.gain(5.0): succeeded
[INFO] 02/27/2024 16:44:45.004 - pyloncamera.py - [CAM Class ] PylonCamera.exposure_t(25.0): succeeded

**Comment by ericweiner** [comment]
there are two timeouts here, let's make them both 50ms.  This page says the windows default is 500 ms...  
https://learn.microsoft.com/en-us/dotnet/api/system.io.ports.serialport.writetimeout?view=dotnet-plat-ext-8.0

**Comment by ericweiner** [comment]
To be specific, this is how I'm testing it now. 

Instead of this:
        self.baudrate=115200
        self.bytesize=serial.EIGHTBITS
        self.parity=serial.PARITY_NONE
        self.stopbits=serial.STOPBITS_ONE
        **self.timeout=0.01 # seconds
        self.write_timeout=0.01 # seconds**
        self.driver = False


I'm using

        self.baudrate=115200
        self.bytesize=serial.EIGHTBITS
        self.parity=serial.PARITY_NONE
        self.stopbits=serial.STOPBITS_ONE
        **self.timeout=0.05 # seconds
        self.write_timeout=0.05 # seconds**
        self.driver = False

**Comment by ericweiner** [comment]
testing the  LED-timeout branch. 
I reset the timeout values to 0.005 (5 ms) in order to have them happen more frequently. 

This the results.  Perhaps we should add a delay before instantly trying to reconnect to the com port?  I think this is just windows blocking access to it temporarily...

[INFO] 02/28/2024 13:18:36.610 - ledboard.py - [LED Class ] LEDBoard.exchange_command(LEDS_OFF) succeeded: 'RE: LEDS_OFF\r\n'
[INFO] 02/28/2024 13:18:36.610 - pyloncamera.py - [CAM Class ] PylonCamera.gain(10.0): succeeded
[INFO] 02/28/2024 13:18:36.610 - pyloncamera.py - [CAM Class ] PylonCamera.exposure_t(25.0): succeeded
[INFO] 02/28/2024 13:18:36.610 - ledboard.py - [LED Class ] LEDBoard.exchange_command(LED3_25) succeeded: 'RE: LEDS_OFF\r\n'
[INFO] 02/28/2024 13:18:36.610 - pyloncamera.py - [CAM Class ] PylonCamera.get_exposure_t(): succeeded
[INFO] 02/28/2024 13:18:36.864 - ledboard.py - [LED Class ] LEDBoard.exchange_command(LEDS_OFF) succeeded: 'LED 0 has been turned off\r\n'
[INFO] 02/28/2024 13:18:36.864 - lumascope_api.py - [SCOPE API ] Lumascope.focus_function()
[INFO] 02/28/2024 13:18:36.927 - lumascope_api.py - [SCOPE API ] Focus Score Vollath: 7732953.0
[INFO] 02/28/2024 13:18:38.099 - ledboard.py - [LED Class ] LEDBoard.exchange_command(LEDS_OFF) succeeded: 'RE: LEDS_OFF\r\n'
[INFO] 02/28/2024 13:18:38.099 - pyloncamera.py - [CAM Class ] PylonCamera.gain(10.0): succeeded
[INFO] 02/28/2024 13:18:38.099 - pyloncamera.py - [CAM Class ] PylonCamera.exposure_t(25.0): succeeded
[INFO] 02/28/2024 13:18:38.099 - ledboard.py - [LED Class ] LEDBoard.exchange_command(LED3_25) succeeded: 'RE: LEDS_OFF\r\n'
[INFO] 02/28/2024 13:18:38.115 - pyloncamera.py - [CAM Class ] PylonCamera.get_exposure_t(): succeeded
[INFO] 02/28/2024 13:18:38.368 - ledboard.py - [LED Class ] LEDBoard.exchange_command(LEDS_OFF) succeeded: ' turned off\r\n'
[INFO] 02/28/2024 13:18:38.368 - lumascope_api.py - [SCOPE API ] Lumascope.focus_function()
[INFO] 02/28/2024 13:18:38.452 - lumascope_api.py - [SCOPE API ] Focus Score Vollath: 7738734.0
[INFO] 02/28/2024 13:18:39.683 - ledboard.py - [LED Class ] LEDBoard.exchange_command(LEDS_OFF) succeeded: 'RE: LEDS_OFF\r\n'
[INFO] 02/28/2024 13:18:39.683 - pyloncamera.py - [CAM Class ] PylonCamera.gain(10.0): succeeded
[INFO] 02/28/2024 13:18:39.699 - pyloncamera.py - [CAM Class ] PylonCamera.exposure_t(25.0): succeeded
[INFO] 02/28/2024 13:18:39.699 - ledboard.py - [LED Class ] LEDBoard.exchange_command(LED3_25) succeeded: 'RE: LEDS_OFF\r\n'
[INFO] 02/28/2024 13:18:39.699 - pyloncamera.py - [CAM Class ] PylonCamera.get_exposure_t(): succeeded
[INFO] 02/28/2024 13:18:39.953 - ledboard.py - [LED Class ] LEDBoard.exchange_command(LEDS_OFF) succeeded: 'turned off\r\n'
[INFO] 02/28/2024 13:18:39.958 - lumascope_api.py - [SCOPE API ] Lumascope.focus_function()
[INFO] 02/28/2024 13:18:40.032 - lumascope_api.py - [SCOPE API ] Focus Score Vollath: 7704005.0
[INFO] 02/28/2024 13:18:41.241 - ledboard.py - [LED Class ] LEDBoard.exchange_command(LEDS_OFF) succeeded: 'RE: LEDS_OFF\r\n'
[INFO] 02/28/2024 13:18:41.241 - pyloncamera.py - [CAM Class ] PylonCamera.gain(10.0): succeeded
[INFO] 02/28/2024 13:18:41.241 - pyloncamera.py - [CAM Class ] PylonCamera.exposure_t(25.0): succeeded
[INFO] 02/28/2024 13:18:41.256 - ledboard.py - [LED Class ] Found LED controller and about to create driver.
[ERROR] 02/28/2024 13:18:41.256 - ledboard.py - [LED Class ] LEDBoard.connect() failed
Traceback (most recent call last):
  File "C:\Users\chris\Downloads\LumaViewPro-fix-led-timeout\ledboard.py", line 117, in exchange_command
    self.driver.write(stream)
  File "C:\Users\chris\AppData\Roaming\Python\Python310\site-packages\serial\serialwin32.py", line 325, in write
    raise SerialTimeoutException('Write timeout')
serial.serialutil.SerialTimeoutException: Write timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\chris\Downloads\LumaViewPro-fix-led-timeout\ledboard.py", line 80, in connect
    self.driver = serial.Serial(port=self.port,
  File "C:\Users\chris\AppData\Roaming\Python\Python310\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\chris\AppData\Roaming\Python\Python310\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\chris\AppData\Roaming\Python\Python310\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM3': PermissionError(13, 'Access is denied.', None, 5)
[WARNING] 02/28/2024 13:18:41.272 - ledboard.py - [LED Class ] LEDBoard.exchange_command(LED3_25) Serial Timeout Occurred, attempt 0
[INFO] 02/28/2024 13:18:41.272 - pyloncamera.py - [CAM Class ] PylonCamera.get_exposure_t(): succeeded
[INFO] 02/28/2024 13:18:41.524 - ledboard.py - [LED Class ] Found LED controller and about to create driver.
[INFO] 02/28/2024 13:18:41.524 - ledboard.py - [LED Class ] LEDBoard.connect() succeeded
[INFO] 02/28/2024 13:18:41.524 - ledboard.py - [LED Class ] LEDBoard.exchange_command(LEDS_OFF) succeeded: '\x04 : Command not recognized\r\n'
[INFO] 02/28/2024 13:18:41.524 - lumascope_api.py - [SCOPE API ] Lumascope.focus_function()
[INFO] 02/28/2024 13:18:41.571 - lumascope_api.py - [SCOPE API ] Focus Score Vollath: 170.0
[INFO] 02/28/2024 13:18:42.763 - ledboard.py - [LED Class ] LEDBoard.exchange_command(LEDS_OFF) succeeded: 'RE: LEDS_OFF\r\n'
[INFO] 02/28/2024 13:18:42.763 - pyloncamera.py - [CAM Class ] PylonCamera.gain(10.0): succeeded
[INFO] 02/28/2024 13:18:42.779 - pyloncamera.py - [CAM Class ] PylonCamera.exposure_t(25.0): succeeded

**Comment by ericweiner** [comment]
Thus far I have only seen this bug occur on one machine, and only during the backlash testing script. 
I have not yet seen it recur with the longer (50ms) timeout in the current branch.  I will continue testing this, but we can probably close this issue for now if I don't see it recur.

**Comment by ericweiner** [comment]
This is in 1.7 release.  Have not seen this issue recur since.
