### ISSUE TITLE
stacktrace if camera is opened in another app

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#331]
(error seen in the "fix-led-timeout" branch)

This is seen in the logs if the Basler camera is opened in the Pylon viewer, for example.

[INFO] 02/28/2024 11:12:52.554 - pyloncamera.py - [CAM Class ] PylonCamera.__init__()
[ERROR] 02/28/2024 11:12:53.531 - pyloncamera.py - [CAM Class ] PylonCamera.connect() failed
Traceback (most recent call last):
  File "C:\Users\chris\Downloads\LumaViewPro-fix-led-timeout\pyloncamera.py", line 60, in connect
    self.active = pylon.InstantCamera(pylon.TlFactory.GetInstance().CreateFirstDevice())
  File "C:\Users\chris\AppData\Roaming\Python\Python310\site-packages\pypylon\pylon.py", line 1601, in CreateFirstDevice
    return _pylon.TlFactory_CreateFirstDevice(self, *args)
_genicam.RuntimeException: Failed to open device '\\?\usb#vid_2676&pid_ba06&mi_00#7&20c51550&1&0000#{79bfeeca-947f-11e1-bc58-001b2163ef96}' for XML file download. Error: 'Device is exclusively opened by another client.' : RuntimeException thrown (file 'pylonusbtl.cpp', line 498)

**Comment by jmcoreymv** [comment]
I dont think the same camera device is allowed to be open in Pylon viewer and LVP at the same time.  It sounds like this is what you are experiencing?

**Comment by ericweiner** [comment]
Correct.  I just wanted to fix the stack trace.

**Comment by jmcoreymv** [comment]
Fix in `main` on https://github.com/EtalumaSupport/LumaViewPro/pull/358

**Comment by ericweiner** [comment]
fixed.
