### ISSUE TITLE
OME Tiff save failure in 1.7.1 app release

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#344]
[INFO] 03/22/2024 11:41:03.661 - pyloncamera.py - [CAM Class ] PylonCamera.get_exposure_t(): succeeded
[ERROR] 03/22/2024 11:41:03.675 - lumascope_api.py - [SCOPE API ] Error: Unable to save. Perhaps save folder does not exist?
Traceback (most recent call last):
  File "lumascope_api.py", line 355, in save_image
    image_utils.write_ome_tiff(
  File "image_utils.py", line 139, in write_ome_tiff
    tif.write(
  File "tifffile\tifffile.py", line 3562, in write
  File "tifffile\tifffile.py", line 22181, in encode_chunks
  File "concurrent\futures\_base.py", line 619, in result_iterator
  File "concurrent\futures\_base.py", line 317, in _result_or_cancel
  File "concurrent\futures\_base.py", line 449, in result
  File "concurrent\futures\_base.py", line 401, in __get_result
  File "concurrent\futures\thread.py", line 58, in run
  File "tifffile\tifffile.py", line 22147, in func
  File "tifffile\tifffile.py", line 3342, in compressionfunc
  File "imagecodecs\imagecodecs.py", line 1225, in stub_encode
imagecodecs.imagecodecs.DelayedImportError: could not import name 'lzw_encode' from 'imagecodecs'
[INFO] 03/22/2024 11:41:08.347 - lumaviewpro.py - [LVP Main  ] CompositeCapture.live_capture()
[INFO] 03/22/2024 11:41:08.507 - lumascope_api.py - [SCOPE API ] Saving Image to C:\Users\Eric Weiner\Documents\OME test\Manual\live_D6_BF_000002.tiff
[INFO] 03/22/2024 11:41:12.060 - lumaviewpro.py - [LVP Main  ] CompositeCapture.live_capture()
[INFO] 03/22/2024 11:41:12.085 - pyloncamera.py - [CAM Class ] PylonCamera.get_exposure_t(): succeeded
[ERROR] 03/22/2024 11:41:12.093 - lumascope_api.py - [SCOPE API ] Error: Unable to save. Perhaps save folder does not exist?
Traceback (most recent call last):
  File "lumascope_api.py", line 355, in save_image
    image_utils.write_ome_tiff(
  File "image_utils.py", line 139, in write_ome_tiff
    tif.write(
  File "tifffile\tifffile.py", line 3562, in write
  File "tifffile\tifffile.py", line 22181, in encode_chunks
  File "concurrent\futures\_base.py", line 619, in result_iterator
  File "concurrent\futures\_base.py", line 317, in _result_or_cancel
  File "concurrent\futures\_base.py", line 449, in result
  File "concurrent\futures\_base.py", line 401, in __get_result
  File "concurrent\futures\thread.py", line 58, in run
  File "tifffile\tifffile.py", line 22147, in func
  File "tifffile\tifffile.py", line 3342, in compressionfunc
  File "imagecodecs\imagecodecs.py", line 1225, in stub_encode
imagecodecs.imagecodecs.DelayedImportError: could not import name 'lzw_encode' from 'imagecodecs'
[INFO] 03/22/2024 11:42:25.748 - lumaviewpro.py - [LVP Main  ] LumaViewProApp.on_stop()
[INFO] 03/22/2024 11:42:25.749 - ledboard.py - [LED Class ] LEDBoard.exchange_command(LEDS_OFF) succeeded: 'RE: LED3_25\r\n'
[INFO] 03/22/2024 11:42:25.750 - lumaviewpro.py - [LVP Main  ] lumaview.scope.leds_off()
[INFO] 03/22/2024 11:42:25.750 - lumaviewpro.py - [LVP Main  ] MicroscopeSettings.save_settings()

**Comment by ericweiner** [comment]
This error only occurs in the app build.  The python code works
