### ISSUE TITLE
Crash in 1.8

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#366]
Running .py in main branch, from 5-21-2024.  Getting crashes.  I wonder if this is a corrupt python install?

[INFO   ] [XYZ Class ] MotorBoard.move_rel_pos(Z,1.0) succeeded
[INFO   ] [LVP Main  ] VerticalControl.focus_iterate()
 Exception ignored in: <function Variable.__del__ at 0x000002B2AD512290>
 Traceback (most recent call last):
   File "C:\Program Files\Python310\lib\tkinter\__init__.py", line 388, in __del__
     if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
 RuntimeError: main thread is not in main loop
[INFO   ] [LVP Main  ] VerticalControl.focus_function()
[INFO   ] [[LVP Main  ] Focus Score Vollath] 61773750.0
Axis: Z steps: 678051
[INFO   ] [XYZ Class ] MotorBoard.move_rel_pos(Z,1.0) succeeded
[INFO   ] [LVP Main  ] VerticalControl.focus_iterate()
[INFO   ] [LVP Main  ] VerticalControl.focus_function()
[INFO   ] [[LVP Main  ] Focus Score Vollath] 61773750.0
Axis: Z steps: 678221
[INFO   ] [XYZ Class ] MotorBoard.move_rel_pos(Z,1.0) succeeded
[INFO   ] [LVP Main  ] ProtocolSettings.protocol_iterate()
[INFO   ] [LVP Main  ] VerticalControl.focus_iterate()
 Exception ignored in: <function Variable.__del__ at 0x000002B2AD512290>
 Traceback (most recent call last):
   File "C:\Program Files\Python310\lib\tkinter\__init__.py", line 388, in __del__
     if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
 RuntimeError: main thread is not in main loop
Tcl_AsyncDelete: async handler deleted by the wrong thread
[INFO   ] [LVP Main  ] VerticalControl.focus_function()

[tcl crash.zip](https://github.com/EtalumaSupport/LumaViewPro/files/15421989/tcl.crash.zip)

The crash in windows says the following:
Faulting application name: python.exe, version: 3.10.11150.1013, time stamp: 0x642cc427
Faulting module name: tcl86t.dll, version: 8.6.2.12, time stamp: 0x61899040
Exception code: 0x80000003
Fault offset: 0x00000000000f8bbd
Faulting process id: 0x0x1558
Faulting application start time: 0x0x1DAABD42497CD60
Faulting application path: C:\Program Files\Python310\python.exe
Faulting module path: C:\Program Files\Python310\DLLs\tcl86t.dll
Report Id: 572a024d-0779-4702-abb0-ca185ed43c17
Faulting package full name: 
Faulting package-relative application ID:

**Comment by ericweiner** [comment]
There were a lot of old pip packages.  I just updated.  I will see if it recurs. 

Installing collected packages: pypylon, kivy-deps.sdl2, kivy-deps.angle, numpy, scipy, pandas, opencv-python, scikit-image, Kivy
  Attempting uninstall: pypylon
    Found existing installation: pypylon 2.2.0
    Uninstalling pypylon-2.2.0:
      Successfully uninstalled pypylon-2.2.0
  Attempting uninstall: kivy-deps.sdl2
    Found existing installation: kivy-deps.sdl2 0.6.0
    Uninstalling kivy-deps.sdl2-0.6.0:
      Successfully uninstalled kivy-deps.sdl2-0.6.0
  Attempting uninstall: kivy-deps.angle
    Found existing installation: kivy-deps.angle 0.3.3
    Uninstalling kivy-deps.angle-0.3.3:
      Successfully uninstalled kivy-deps.angle-0.3.3
  Attempting uninstall: numpy
    Found existing installation: numpy 1.25.1
    Uninstalling numpy-1.25.1:
      Successfully uninstalled numpy-1.25.1
  WARNING: The script f2py.exe is installed in 'C:\Users\chris\AppData\Roaming\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Attempting uninstall: scipy
    Found existing installation: scipy 1.11.1
    Uninstalling scipy-1.11.1:
      Successfully uninstalled scipy-1.11.1
  Attempting uninstall: pandas
    Found existing installation: pandas 2.0.3
    Uninstalling pandas-2.0.3:
      Successfully uninstalled pandas-2.0.3
  Attempting uninstall: opencv-python
    Found existing installation: opencv-python 4.8.0.74
    Uninstalling opencv-python-4.8.0.74:
      Successfully uninstalled opencv-python-4.8.0.74
  Attempting uninstall: scikit-image
    Found existing installation: scikit-image 0.21.0
    Uninstalling scikit-image-0.21.0:
      Successfully uninstalled scikit-image-0.21.0
  Attempting uninstall: Kivy
    Found existing installation: Kivy 2.2.1
    Uninstalling Kivy-2.2.1:
      Successfully uninstalled Kivy-2.2.1
Successfully installed Kivy-2.3.0 kivy-deps.angle-0.4.0 kivy-deps.sdl2-0.7.0 numpy-1.26.4 opencv-python-4.9.0.80 pandas-2.2.1 pypylon-3.0.1 scikit-image-0.22.0 scipy-1.12.0

**Comment by ericweiner** [comment]
This has not recurred in 5 days of continuous imaging since updating the requirements. I will close this in 1 week if it does not reappear.

**Comment by ericweiner** [comment]
Closing. I have not see this recur.
