### ISSUE TITLE
Can't get LV Pro to startup.

### ISSUE THREAD

**Issue by ericweiner** [EtalumaSupport/LumaViewPro#92]
I ran the 
>python -m pip install pywinusb

And updated PIP to 2.2.  But it still will not start up.  This is Proto1, on windows 11.  It is finding the motor controller board but not able to connect to it for some reason.  

This is the message that I get in the console.  I don't understand the file not found error at the end.  It is clearly there... 

C:\Users\Lumaview Pro>python "C:\Users\Lumaview Pro\Documents\LumaViewPro-master\lumaviewpro.py"
[INFO   ] [Logger      ] Record log in C:\Users\Lumaview Pro\.kivy\logs\kivy_22-07-26_7.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.2
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.1
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.4.5
[INFO   ] [Kivy        ] v2.1.0
[INFO   ] [Kivy        ] Installed at "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\python.exe"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 189 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 - Build 30.0.101.1338'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) UHD Graphics'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 - Build 30.0.101.1338'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
LED Control Board v3 identified at COM4
[INFO   ] [MCP2210     ] opening device: MCP2210 (serial: 0001011361, VID: 0x04D8, PID: 0x00DE)
Found Device MCP2210 (serial: 0001011361, VID: 0x04D8, PID: 0x00DE)
Could not connect to Motor Control Board
LumaViewPro compatible camera is now connected.
[INFO   ] [GL          ] NPOT texture support is available
 Traceback (most recent call last):
   File "C:\Users\Lumaview Pro\Documents\LumaViewPro-master\lumaviewpro.py", line 2030, in <module>
     LumaViewProApp().run()
   File "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\app.py", line 954, in run
     self._run_prepare()
   File "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\app.py", line 924, in _run_prepare
     root = self.build()
   File "C:\Users\Lumaview Pro\Documents\LumaViewPro-master\lumaviewpro.py", line 2012, in build
     lumaview = MainDisplay()
   File "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\uix\floatlayout.py", line 65, in __init__
     super(FloatLayout, self).__init__(**kwargs)
   File "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\uix\layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\uix\widget.py", line 366, in __init__
     self.apply_class_lang_rules(
   File "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\uix\widget.py", line 470, in apply_class_lang_rules
     Builder.apply(
   File "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\lang\builder.py", line 540, in apply
     self._apply_rule(
   File "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\lang\builder.py", line 660, in _apply_rule
     child.apply_class_lang_rules(
   File "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\uix\widget.py", line 470, in apply_class_lang_rules
     Builder.apply(
   File "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\lang\builder.py", line 540, in apply
     self._apply_rule(
   File "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\lang\builder.py", line 662, in _apply_rule
     self._apply_rule(
   File "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\lang\builder.py", line 662, in _apply_rule
     self._apply_rule(
   File "C:\Users\Lumaview Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\kivy\lang\builder.py", line 658, in _apply_rule
     child = cls(__no_builder=True)
   File "C:\Users\Lumaview Pro\Documents\LumaViewPro-master\lumaviewpro.py", line 1044, in __init__
     with open('./data/labware.json', "r") as read_file:
 FileNotFoundError: [Errno 2] No such file or directory: './data/labware.json'

**Comment by iwaniec** [comment]
The program needs to be run from the directory that it is in because it looks for relative directories using ./ and ../ This is something that should be corrected. At the moment, please see if you are in a different working directory.

**Comment by ericweiner** [comment]
Ah, ok.  I had two overlapping problems.  It didn't startup when I ran the python directly, which was due to an unrelated problem (one thing wasn't powered up).  But then I went to the command line to try to see what the console was saying, but didn't CD to the right directory first...  

Closing...
